# Generated by Django 3.0.4 on 2020-04-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph_notes', '0002_auto_20200414_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='note',
            new_name='notes',
        ),
    ]
