# Generated by Django 3.0.4 on 2020-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_notes', '0003_auto_20200414_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='graph_notes.Tag'),
        ),
    ]
